/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.vektorel.desktopapplication.gui;

import com.vektorel.desktopapplication.data.SettlementService;
import com.vektorel.desktopapplication.data.StaffService;
import com.vektorel.desktopapplication.data.dto.City;
import com.vektorel.desktopapplication.data.dto.District;
import com.vektorel.desktopapplication.data.dto.Staff;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author uto
 */
public class DlgUpdatingStaff extends javax.swing.JDialog {

    SettlementService ss = new SettlementService();
    Long stfId = -1L;

    public DlgUpdatingStaff(java.awt.Frame parent, boolean modal, Long staffId) {
        super(parent, modal);
        initComponents();
        this.stfId = staffId;
        fillingCity();
        fillingDistrict(cmbCity.getSelectedItem().toString());
        display(staffId);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtSurname = new javax.swing.JTextField();
        txtPhoneNo = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtOffAdr = new javax.swing.JTextField();
        txtAddr = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmbCity = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        cmbDistrict = new javax.swing.JComboBox();
        btnSave = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("First Name:");

        jLabel2.setText("Last Name:");

        jLabel3.setText("Phone Number:");

        jLabel4.setText("Email:");

        jLabel5.setText("Office Address:");

        jLabel6.setText("Build Address:");

        jLabel7.setText("City:");

        cmbCity.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCityİtemStateChanged(evt);
            }
        });

        jLabel8.setText("District:");

        btnSave.setText("Update");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 89, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtName)
                                .addComponent(txtSurname)
                                .addComponent(txtPhoneNo)
                                .addComponent(txtEmail)
                                .addComponent(txtOffAdr)
                                .addComponent(txtAddr)
                                .addComponent(cmbCity, 0, 124, Short.MAX_VALUE)))
                        .addContainerGap(141, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCancel)
                        .addGap(48, 48, 48)
                        .addComponent(btnSave)
                        .addGap(99, 99, 99))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(txtOffAdr, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(txtAddr, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbDistrict, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancel))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbCityİtemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCityİtemStateChanged
         fillingDistrict(cmbCity.getSelectedItem().toString());
    }//GEN-LAST:event_cmbCityİtemStateChanged

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        Staff s = new Staff();
        StaffService staffService = new StaffService();
        s.setId(stfId);
        s.setName(txtName.getText());
        s.setSurname(txtSurname.getText());
        s.setPhoneNumber(txtPhoneNo.getText());
        s.setEmail(txtEmail.getText());
        s.setOfficeAddress(txtOffAdr.getText());
        s.setAddress(txtAddr.getText());
        s.setCity(getCityId(cmbCity.getSelectedItem().toString()));
        s.setDistrict(getDistrictId(cmbDistrict.getSelectedItem().toString()));
        staffService.update(s);
        this.dispose();
    }//GEN-LAST:event_btnSaveActionPerformed

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox cmbCity;
    private javax.swing.JComboBox cmbDistrict;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtAddr;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtOffAdr;
    private javax.swing.JTextField txtPhoneNo;
    private javax.swing.JTextField txtSurname;
    // End of variables declaration//GEN-END:variables

    private void display(Long staffId) {
        StaffService ss = new StaffService();

        SettlementService ss1 = new SettlementService();

        Staff s = ss.getById(staffId);

        txtName.setText(s.getName());
        txtSurname.setText(s.getSurname());
        txtPhoneNo.setText(s.getPhoneNumber());
        txtEmail.setText(s.getEmail());
        txtOffAdr.setText(s.getOfficeAddress());
        txtAddr.setText(s.getAddress());

         cmbCity.setSelectedItem(ss1.getCity(s.getCity()).getCityName());
         cmbDistrict.setSelectedItem(ss1.getDistrict(s.getDistrict()).getDistrictName());
        










    
    }
    List<City> cityList;
    List<District> districtList;

    public void fillingCity() {
        cityList = ss.getAllCity();
        String[] cityArray = new String[cityList.size()];

        for (int i = 0; i < cityList.size(); i++) {
            cityArray[i] = cityList.get(i).getCityName();
        }
        cmbCity.setModel(new DefaultComboBoxModel(cityArray));

    }

    public void fillingDistrict(String cityName) {
        districtList = ss.getDistrictsByCityName(cityName);
        String[] districtArray = new String[districtList.size()];

        for (int i = 0; i < districtList.size(); i++) {
            districtArray[i] = districtList.get(i).getDistrictName();

        }

        cmbDistrict.setModel(new DefaultComboBoxModel(districtArray));
    }

    public Long getCityId(String cityName) {
        for (City city : cityList) {
            if (city.getCityName().equals(cityName)) {
                return city.getId();
            }
        }
        return -1L;
    }

    public Long getDistrictId(String districtName) {
        for (District district : districtList) {
            if (district.getDistrictName().equals(districtName)) {
                return district.getId();
            }
        }
        return -1L;


    }
}
